/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package form;


import com.mysql.cj.xdevapi.PreparableStatement;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

  
/**
 *
 * @author priya
 */
public class PaymentForm extends javax.swing.JInternalFrame {

   

    /**
     * Creates new form paymentForm
     */
    public PaymentForm() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RadioButton = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        OrderNameTxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        BuildingPriceTxt = new javax.swing.JTextField();
        LargeLandTxt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        TotalPriceTxt = new javax.swing.JTextField();
        PpnTxt = new javax.swing.JTextField();
        InstalmentMounTxt = new javax.swing.JTextField();
        simpanButton = new javax.swing.JButton();
        prosesButton = new javax.swing.JButton();
        AreaCombo = new javax.swing.JComboBox<>();
        T36 = new javax.swing.JRadioButton();
        T45 = new javax.swing.JRadioButton();
        T56 = new javax.swing.JRadioButton();
        hapusButton = new javax.swing.JButton();
        DpTxt = new javax.swing.JTextField();
        InstalAmounTxt = new javax.swing.JTextField();
        AggreeCek = new javax.swing.JCheckBox();
        AvailableLandTxt = new javax.swing.JTextField();
        PriceLandTxt = new javax.swing.JTextField();

        setTitle("FORM PENJUALAN");

        jLabel1.setText("Nama Pemesan");

        jLabel2.setText("Harga Tanah");

        jLabel3.setText("Area");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/form/img2.jpg"))); // NOI18N

        jLabel5.setText("Harga Rumah");

        jLabel6.setText("Tipe Rumah");

        jLabel7.setText("Luas Tanah Asli");

        BuildingPriceTxt.setEditable(false);
        BuildingPriceTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        LargeLandTxt.setEditable(false);
        LargeLandTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel8.setText("Luas Tanah Tersedia");

        jLabel9.setText("Harga");

        jLabel10.setText("DP");

        jLabel11.setText("Lama Cicilan");

        jLabel12.setText("PPN (10%)");

        jLabel13.setText("Cicilan / bulan");

        jLabel14.setText("Bulan");

        TotalPriceTxt.setEditable(false);
        TotalPriceTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        PpnTxt.setEditable(false);
        PpnTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        InstalmentMounTxt.setEditable(false);
        InstalmentMounTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        simpanButton.setText("SIMPAN");
        simpanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanButtonActionPerformed(evt);
            }
        });

        prosesButton.setText("PROSES");
        prosesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prosesButtonActionPerformed(evt);
            }
        });

        AreaCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "==pilih==", "Bougetvile", "Melati", "Flamboyan" }));
        AreaCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AreaComboActionPerformed(evt);
            }
        });

        RadioButton.add(T36);
        T36.setText("T -36");
        T36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T36ActionPerformed(evt);
            }
        });

        RadioButton.add(T45);
        T45.setText("T -45");
        T45.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T45ActionPerformed(evt);
            }
        });

        RadioButton.add(T56);
        T56.setText("T -56");
        T56.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T56ActionPerformed(evt);
            }
        });

        hapusButton.setText("HAPUS");
        hapusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusButtonActionPerformed(evt);
            }
        });

        DpTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        InstalAmounTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        AggreeCek.setText("Setuju");
        AggreeCek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AggreeCekActionPerformed(evt);
            }
        });

        AvailableLandTxt.setEditable(false);
        AvailableLandTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        PriceLandTxt.setEditable(false);
        PriceLandTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 295, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(18, 18, 18))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(33, 33, 33)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(76, 76, 76)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(OrderNameTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                            .addComponent(AreaCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PriceLandTxt))))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10)
                            .addComponent(jLabel12))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(54, 54, 54)
                                    .addComponent(simpanButton)
                                    .addGap(18, 18, 18)
                                    .addComponent(hapusButton)
                                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(PpnTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(InstalAmounTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jLabel14)))
                                    .addContainerGap(84, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(17, 17, 17)
                                        .addComponent(DpTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(InstalmentMounTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(AggreeCek)))
                                .addContainerGap())))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(T36)
                                    .addComponent(T56))
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(59, 59, 59))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(T45)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(TotalPriceTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                            .addComponent(LargeLandTxt)
                            .addComponent(BuildingPriceTxt)
                            .addComponent(AvailableLandTxt)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addComponent(prosesButton)
                        .addGap(302, 302, 302))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(OrderNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(PriceLandTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(AreaCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(BuildingPriceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LargeLandTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(T36))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(T45))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(T56)
                            .addComponent(AvailableLandTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(TotalPriceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(DpTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jLabel14)
                            .addComponent(InstalAmounTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PpnTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(InstalmentMounTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AggreeCek))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(simpanButton)
                    .addComponent(prosesButton)
                    .addComponent(hapusButton))
                .addGap(46, 46, 46))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AreaComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AreaComboActionPerformed
        switch (AreaCombo.getSelectedIndex()) { 
            case 0: {
                PriceLandTxt.setText("");
                BuildingPriceTxt.setText("");
                RadioButton.clearSelection();
                LargeLandTxt.setText("");
                AvailableLandTxt.setText("");
                TotalPriceTxt.setText("");
                DpTxt.setText("");
                InstalAmounTxt.setText("");
                InstalmentMounTxt.setText("");
                PpnTxt.setText("");
                AggreeCek.setSelected(false);
            }
            case 1:{
            PriceLandTxt.setText("");
            BuildingPriceTxt.setText("");
            RadioButton.clearSelection();
            LargeLandTxt.setText("");
            AvailableLandTxt.setText("");
            TotalPriceTxt.setText("");
            DpTxt.setText("");
            InstalAmounTxt.setText("");
            InstalmentMounTxt.setText("");
            PpnTxt.setText("");
            AggreeCek.setSelected(false);
            }
           case 2:{
                PriceLandTxt.setText("600000");
                BuildingPriceTxt.setText("120000000");
                RadioButton.clearSelection();
                LargeLandTxt.setText("");
                AvailableLandTxt.setText("");
                TotalPriceTxt.setText("");
                DpTxt.setText("");
                InstalAmounTxt.setText("");
                InstalmentMounTxt.setText("");
                PpnTxt.setText("");
                AggreeCek.setSelected(false);
            }
           default:{
                    PriceLandTxt.setText("700000");
                    BuildingPriceTxt.setText("150000000");
                    RadioButton.clearSelection();
                    LargeLandTxt.setText("");
                    AvailableLandTxt.setText("");
                    TotalPriceTxt.setText("");
                    DpTxt.setText("");
                    InstalAmounTxt.setText("");
                    InstalmentMounTxt.setText("");
                    PpnTxt.setText("");
                    AggreeCek.setSelected(false);
            }
        }
        
    }//GEN-LAST:event_AreaComboActionPerformed

    private void T36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T36ActionPerformed
        if(AreaCombo.getSelectedIndex()== 0){
            RadioButton.clearSelection();
        }else{
            LargeLandTxt.setText("90");
            AvailableLandTxt.setText("54");
            long landPrice = Long.parseLong(PriceLandTxt.getText()),buildingPrice = Long.parseLong(BuildingPriceTxt.getText()),availableLand = Long.parseLong(AvailableLandTxt.getText()), totalPrice;
            totalPrice = (availableLand * landPrice) + buildingPrice;
            TotalPriceTxt.setText(""+totalPrice);
            InstalAmounTxt.setText("");                  
            DpTxt.setText("");
            PpnTxt.setText("");
            InstalmentMounTxt.setText("");
        }
        
    }//GEN-LAST:event_T36ActionPerformed

    private void T45ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T45ActionPerformed
       if(AreaCombo.getSelectedIndex()== 0){
            RadioButton.clearSelection();
        }else{
            LargeLandTxt.setText("120");
            AvailableLandTxt.setText("75");
            long landPrice = Long.parseLong(PriceLandTxt.getText()),buildingPrice = Long.parseLong(BuildingPriceTxt.getText()),availableLand = Long.parseLong(AvailableLandTxt.getText()), totalPrice;
            totalPrice = (availableLand * landPrice) + buildingPrice;
            TotalPriceTxt.setText(""+totalPrice);       
            InstalAmounTxt.setText("");
            DpTxt.setText("");
            PpnTxt.setText("");
            InstalmentMounTxt.setText("");
            
        }

    }//GEN-LAST:event_T45ActionPerformed

    private void T56ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T56ActionPerformed
        if(AreaCombo.getSelectedIndex()== 0){
            RadioButton.clearSelection();
        }else{
            LargeLandTxt.setText("140");
            AvailableLandTxt.setText("95");
            long landPrice = Long.parseLong(PriceLandTxt.getText()),buildingPrice = Long.parseLong(BuildingPriceTxt.getText()),availableLand = Long.parseLong(AvailableLandTxt.getText()), totalPrice;
            totalPrice = (availableLand * landPrice) + buildingPrice;
            TotalPriceTxt.setText(""+totalPrice);
            InstalAmounTxt.setText("");
            DpTxt.setText("");
            PpnTxt.setText("");
            InstalmentMounTxt.setText("");
        }
    }//GEN-LAST:event_T56ActionPerformed

    private void hapusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusButtonActionPerformed
        OrderNameTxt.setText("");
        PriceLandTxt.setText("");
        BuildingPriceTxt.setText("");
        LargeLandTxt.setText("");
        AvailableLandTxt.setText("");
        TotalPriceTxt.setText("");
        DpTxt.setText("");
        InstalAmounTxt.setText("");
        InstalmentMounTxt.setText("");
        PpnTxt.setText("");
        AreaCombo.setSelectedIndex(0);
        RadioButton.clearSelection();
        AggreeCek.setSelected(false);

    }//GEN-LAST:event_hapusButtonActionPerformed

    private void prosesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prosesButtonActionPerformed
        if(TotalPriceTxt.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "pilihan belum lengkap");
            }else if(DpTxt.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "DP belum di isi");
            }else if(InstalAmounTxt.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Isi jumblah yang di inginkan");
            }else{
                long landPrice = Long.parseLong(PriceLandTxt.getText()), buildingPrice = Long.parseLong(BuildingPriceTxt.getText()), availableLand = Long.parseLong(AvailableLandTxt.getText()), DP = Long.parseLong(DpTxt.getText()), instalAmoun = Long.parseLong(InstalAmounTxt.getText()), totalPrice, PPN, InstalPerMounth;
                totalPrice = (availableLand*landPrice) + buildingPrice;
                PPN = totalPrice*10/100;
                InstalPerMounth = (totalPrice + PPN) /instalAmoun;
                PpnTxt.setText(""+PPN);
                InstalmentMounTxt.setText(""+InstalPerMounth);
            }
                
    }//GEN-LAST:event_prosesButtonActionPerformed

    private void AggreeCekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AggreeCekActionPerformed
        if (OrderNameTxt.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "nama pemesan harus di isi");
            AggreeCek.setSelected(false);
       }else if(PpnTxt.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "klik tombol proses dahulu");
            AggreeCek.setSelected(false);
       }else if(PpnTxt.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "klik tombol proses dahulu!");
       }else if(AggreeCek.isSelected()== true){
            JOptionPane.showMessageDialog(null, "pesanan disetujui");
            AggreeCek.setSelected(true);
       }else{
        JOptionPane.showMessageDialog(null, "pesanan belum disetujui");
        AggreeCek.setSelected(false);
        }

    }//GEN-LAST:event_AggreeCekActionPerformed

    private void simpanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanButtonActionPerformed
        if(AggreeCek.isSelected() == false) {
            JOptionPane.showMessageDialog(null, "klik kondirmasi centangbox", "ERROR", JOptionPane.ERROR_MESSAGE);
       } else {
            String typeHouse;
            if (T36.isSelected()){
                typeHouse = "TIPE 36";                                   
            }else if(T45.isSelected()){
                typeHouse = "TIPE 45";
            }else {
                typeHouse = "TIPE 56";
            }
            
            try{
                String sql = "INSERT INTO rumah(Nama,Area,Tipe,Luas,Harga,Jumblah_Cicilan,Cicilan_bulan) VALUES ('"
                        + OrderNameTxt.getText() + "','"  
                        + AreaCombo.getSelectedItem() + "','"
                        + typeHouse + "','"
                        + LargeLandTxt.getText()+ "','"
                        + TotalPriceTxt.getText()+ "','"
                        + InstalAmounTxt.getText()+ "','"
                        + InstalmentMounTxt.getText()+"')";
            Connection conn = (Connection)koneksi.connectDatabse();
                PreparableStatement pst = (PreparableStatement) conn.prepareStatement(sql);
            pst.execute();
            } catch (SQLException ex) {
                Logger.getLogger(PaymentForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            OptionMenu OptionMenu = new OptionMenu();
            OptionMenu.setVisible(true);
            this.getDesktopPane().add(OptionMenu);
            this.dispose();
        }
    }//GEN-LAST:event_simpanButtonActionPerformed

   

    /**
     * @param args the command line arguments
     */
   
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox AggreeCek;
    private javax.swing.JComboBox<String> AreaCombo;
    private javax.swing.JTextField AvailableLandTxt;
    private javax.swing.JTextField BuildingPriceTxt;
    private javax.swing.JTextField DpTxt;
    private javax.swing.JTextField InstalAmounTxt;
    private javax.swing.JTextField InstalmentMounTxt;
    private javax.swing.JTextField LargeLandTxt;
    private javax.swing.JTextField OrderNameTxt;
    private javax.swing.JTextField PpnTxt;
    private javax.swing.JTextField PriceLandTxt;
    private javax.swing.ButtonGroup RadioButton;
    javax.swing.JRadioButton T36;
    javax.swing.JRadioButton T45;
    javax.swing.JRadioButton T56;
    private javax.swing.JTextField TotalPriceTxt;
    private javax.swing.JButton hapusButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton prosesButton;
    private javax.swing.JButton simpanButton;
    // End of variables declaration//GEN-END:variables
}